server:
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
spring:
  datasource:
    clients:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: mysql
      url: jdbc:mysql://localhost/client_db
      username: devuser01
    employees:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: mysql
      url: jdbc:mysql://localhost/employee_db
      username: devuser01
    book:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: mysql
      url: jdbc:mysql://localhost/book_db
      username: devuser01
  servlet:
       multipart:
        max-file-size: 20MB
        max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: none;
    